    ORG 100

start:
        
MOV WORD PTR [0120h],0FFFFH  ;Carpanin 16-0 bitini bellege yerlestirdim
MOV WORD PTR [0122h],0FFFFH   ;Carpanin 32-16 bitini bellege yerlestirdim
MOV WORD PTR [0124h],0FFFFH   ;Carpilanin 16-0 bitini bellege yerlestirdim
MOV WORD PTR [0126h],0FFFFH   ;Carpilanin 32-16 bitini bellege yerlestirdim

MOV WORD PTR [0130h],0000h  ;CARPIMIN 16-0  arasinin bellek adresi
MOV WORD PTR [0132h],0000h  ;CARPIMIN 32-16 arasinin bellek adresi
MOV WORD PTR [0134h],0000h  ;CARPIMIN 48-32 arasinin bellek adresi
MOV WORD PTR [0136h],0000h  ;CARPIMIN 64-48 arasinin bellek adresi

SUB AX,AX
SUB BX,BX
SUB CX,CX
SUB DX,DX
SUB SI,SI
SUB DI,DI


MOV SI,32       ;Dongu sayacimiz Dec olarak 32      

tekrar:

MOV BX,[120h]  ; CARPANİN 16-0 BİTİNİ DIYA AKTAR
AND BX,01H 	; CARPANİN LSB'SI DIŞINDA DİĞER BİTLERİ 0LA ANDLE YANİ 0 YAP (LSBYİ 1 LE ANDLE YANİ LSB ONCEDEN NEYSE SONRADAN DA O OLACAK)
XOR BX,01H	; CARPANİN LSB BİTİ 0 MI DİYE KONTROL ET 0 SA ZERO FLAG 0  A EŞİTLENİR
JZ topla_kaydir ; CARPANİN LSB BİTİ 1 İSE ZERO FLAG 1 E EŞİTLENİR VE JZ DEKİ FONKSİYONA GİT
CLC	; CARPANİN LSB BİTİ 1 DEGİLDİR ZERO FLAG 0 DIR CARRYİ TEMİZLE


devam:

MOV AX,[0136h]
RCR AX,1        ;CARPIM SONUCUNUN 64-48 BİTİNİ BİR SAGA KAYDIR
MOV [0136h],AX
MOV BX,[0134h]      
RCR BX,1        ;CARPIM SONUCUNUN 48-32 BİTİNİ BİR SAGA KAYDIR
MOV [0134h],BX
MOV CX,[0132h]
RCR CX,1        ;CARPIM SONUCUNUN 32-16 BİTİNİ BİR SAGA KAYDIR
MOV [0132h],CX	
MOV DX,[0130h]
RCR DX,1        ;CARPIM SONUCUNUN 16-0  BİTİNİ BİR SAGA KAYDIR
MOV [0130h],DX	  
MOV AX,[0122h]
SHR AX,1        ;CARPANİ BİR BİT SAGA KAYDIR
MOV [0122h],AX 
MOV BX,[0120h]
RCR BX,1        ;CARPANİ BİR BİT SAGA KAYDIR AMA CARRY İLE BİRLİKTE GELİRSE YANİ CARPANİN 32-16 BİTİNDEN GELEN ELDEYİ DE KULLANARAK
MOV [0120h],BX 
   		
DEC SI		;DONGU DEGİSKENİNİ AZALT
CMP SI,0	;DEGİSKEN 0 MI DİYE BAK	
JNZ tekrar	;SIFIR DEGİ, KONTROLCUYE GİT
JMP son		;UYGULAMAYI BİTİRMEYE GİT 


topla_kaydir: 

MOV DX,[0124h]	;DX'E CARPILANIN 16-0 BİTİNİ KOPYALA
ADD [0134h],DX  ;CARPIMIN 48-32 BITINE BURADA CARRY ONEMLI DEGIL
MOV DX,[0126h]  ;DX'E CARPILANIN 32-16 BITINI KOPYALA
ADC [0136h],DX  ;CARPIMIN 64-48 BITINE CARRY I GOZ ONUNE ALARAK ATA
JMP devam  


son:

HLT		;SONUCLAR MSB DEN LSB YE 0136H-0130H BELLEK GOZLERINDE TUTULMAKTADIR






